# Generated by Django 5.2.11 on 2026-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assad_backend', '0002_category_product_productimage_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_business_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('type_of_business', models.CharField(choices=[('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership'), ('Pvt Ltd', 'Pvt Ltd'), ('Ltd Co', 'Ltd Co'), ('Other', 'Other')], max_length=50)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('primary_contact_person', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_contact_person', models.CharField(blank=True, max_length=150)),
                ('years_in_operation', models.CharField(max_length=50)),
                ('nature_of_business', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Distribution', 'Distribution'), ('Online', 'Online'), ('Other', 'Other')], max_length=50)),
                ('main_product_categories', models.TextField()),
                ('geographical_coverage', models.CharField(max_length=255)),
                ('number_of_employees', models.CharField(blank=True, max_length=50)),
                ('annual_turnover', models.CharField(blank=True, max_length=80)),
                ('warehouse_facility', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('warehouse_details', models.TextField(blank=True)),
                ('existing_dealerships', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
    ]
