# Generated by Django 5.2.11 on 2026-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assad_backend', '0006_order_courier_name_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_url',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='India', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
